/*List<Producto> productoShop = [
    Producto(
      id: '1',
      nombre: 'Coca Cola',
      nombreEmpresa: 'Coca Cola Company',
      descripcion: 'estee una coca de 600ml',
      precio: '16',
      imagen: 'lib/images/coca-cola.jpg',
    ),
    Producto(
      id: '2',
      nombre: 'Chips2',
      nombreEmpresa: 'Barcel',
      descripcion: 'papitas sabor fuegoo',
      precio: '40',
      imagen: 'lib/images/chips_fuego.jpg',
    ),
    Producto(
      id: '3',
      nombre: 'Chips3',
      nombreEmpresa: 'Barcel',
      descripcion: 'papitas sabor fuegoo',
      precio: '40',
      imagen: 'lib/images/chips_fuego.jpg',
    ),
    Producto(
      id: '4',
      nombre: 'Chips4',
      nombreEmpresa: 'Barcel',
      descripcion: 'papitas sabor fuegoo',
      precio: '40',
      imagen: 'lib/images/chips_fuego.jpg',
    ),
    Producto(
      id: '5',
      nombre: 'Chips5',
      nombreEmpresa: 'Barcel',
      descripcion: 'papitas sabor fuegoo',
      precio: '40',
      imagen: 'lib/images/chips_fuego.jpg',
    ),
  ];*/