// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2SVeATtGSRoqbZPRzzJeMOZrD1GQDVfk',
    appId: '1:20063354370:web:d0486c51954f892785f11b',
    messagingSenderId: '20063354370',
    projectId: 'auth-2c9aa',
    authDomain: 'auth-2c9aa.firebaseapp.com',
    storageBucket: 'auth-2c9aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqhFb-w4iLtgBKOxgSAGd3SHJrY7RzTDo',
    appId: '1:20063354370:android:136f42c13a6246bb85f11b',
    messagingSenderId: '20063354370',
    projectId: 'auth-2c9aa',
    storageBucket: 'auth-2c9aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7CSAj-VFvk5Cvq5G5xeefguWZL89gAYA',
    appId: '1:20063354370:ios:dfb9e96ed575983f85f11b',
    messagingSenderId: '20063354370',
    projectId: 'auth-2c9aa',
    storageBucket: 'auth-2c9aa.appspot.com',
    iosClientId: '20063354370-40vivoe2178f73k4vdq7547up34e9jq1.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7CSAj-VFvk5Cvq5G5xeefguWZL89gAYA',
    appId: '1:20063354370:ios:dfb9e96ed575983f85f11b',
    messagingSenderId: '20063354370',
    projectId: 'auth-2c9aa',
    storageBucket: 'auth-2c9aa.appspot.com',
    iosClientId: '20063354370-40vivoe2178f73k4vdq7547up34e9jq1.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
